### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by Dheeraj-kumar626** [gregberger/Telnet_resume#1]
I'm new to opensource
I have done npm install then npm start  
I got 
``
> telnet_resume@1.0.0 start /Hacktober/Telnet_resume
> node resume_server.js "resume_server.js"
listening on port 11111

It's waiting for something..
then I opened another tab in the terminal and typed 
`$telnet paperpixel.net 11111`
i was getting _telnet: Unable to connect to remote host: Connection refused_

Am I approaching It in wrong way?
if so can you please provide a detailed explanation of how to use this
Thanks!!

**Comment by gregberger** [comment]
Gosh this is a pretty old dirty project ;) 

The moment you start the server on your machine, the node script listens on your computer's `11111` port. 
The telnet command should use `localhost` or `127.0.0.1` as an address => try `telnet 127.0.0.1 11111` in your terminal
You should then be able to connect to the server.
